Feature: set3

Background: User is Logged In
 	Given navigate to given URL "https://dmr-qa.exela.global/#/login" 
	Then enter username as "septclient"
	Then click on next button
	Then enter Password as "Pa$$w0rd"
	And click on signin button
@Yes
Scenario: To check whether user is able to ingest the large file and can be viewed in Inbox view
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Batch_Name|Testing|12345|
|Batch_ID|Testing|12345|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then Click on profile picture
And logout

@Yes
Scenario: To verify whether the user can add the retention period for a specific Client
Then click on toggle menu
Then click on left pane menu "Client Setup"
When   click on edit.
Then enter max retention period in days as "15"
Then enter retention period in days for deleted iteams as "15"
When   click on save button
Then System should throw a toggle message as "Client has been updated successfully"
Then Click on profile picture
And logout
@prodkss
Scenario: To verify Chain of custody report for selected range of clients mail
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Chain of Custody Report"
Then select from date as "01/01/2021"
Then by default system should display "10" records as selected
Then system should display the record options as "10,25,50,100"
Then user selects "25" as option then system should display "25" records
Then user selects "50" as option then system should display "50" records
Then user selects "100" as option then system should display "100" records
Then user clicks on Next/Right arrow key then system should display next "101 - 200" records
Then click on download icon
Then Click on profile picture
And logout
@prodkss
Scenario: To verify Inventory report for selected range of clients mail
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Inventory Report"
Then select from date as "01/01/2021"
Then by default system should display "10" records as selected
#When click on pagination dropdown
Then system should display the record options as "10,25,50,100"
Then user selects "25" as option then system should display "25" records
Then user selects "50" as option then system should display "50" records
Then user selects "100" as option then system should display "100" records
Then user clicks on Next/Right arrow key then system should display next "101 - 200" records
Then click on download icon
Then Click on profile picture
And logout
@Yes
Scenario: To check whether error toaster appears when user select To date more than 31 days
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Volume Report"
When select from date as "01/01/2021" and to date as "02/15/2021"
Then System should throw a toggle message as "Date Range cannot be more than 31 days period"
Then Click on profile picture
And logout
##need to execute
Scenario: To check whether the report drill down logic changes when user opens report with data more than 100 records
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Volume Report"
Then user selects "100" as option then system should display "100" records
Then user clicks on Next/Right arrow key then system should display next "101 - 201" records
Then Click on profile picture
And logout
@yes
Scenario: To check whether user is able to ingest the large file and can be viewed in Inbox view
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Batch_Name|Testing|12345|
|Batch_ID|Testing|12345|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then Click on profile picture
And logout

#Scenario: 
#Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
#|FieldName|CapturedValue|Value|
#|Batch_Name|Testing|12345|
#|Batch_ID|Testing|12345|
#Then ingest the above zipped file to Azure Blob Storage
#Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
#Then enter username as "septclient"
#Then click on next button
#Then enter Password as "Pa$$w0rd"
#And click on signin button
#Then Click on profile picture
#Then Click on SwitchTo option
#Then Switch to "Mail Admin(Mail User)"
#Then click OK button
#Then filter "autogeneratedDCN" and verify it is available
#Then filter the DCN "autogeneratedDCN"
#Then double click to open the email

@yes
Scenario: To check whether error toaster appears when user select To date more than 31 days
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Reconciliation Report"
When select from date as "01/01/2021" and to date as "02/15/2021"
Then System should throw a toggle message as "Date Range cannot be more than 31 days period"
Then Click on profile picture
And logout
@prodkss
Scenario: To check that report drill down logic changes when user opens report with data more than 100
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Reconciliation Report"
Then filter the received date as "01/02/2020"
Then click on volume received count
Then user selects "100" as option then system should display "100" records
Then user clicks on Next/Right arrow key then system should display next "101 - 200" records
Then Click on profile picture
And logout
@prodkss
Scenario: To check that only 10 records are displayed by default and can change to 25, 50 or 100
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Reconciliation Report"
Then filter the received date as "01/02/2020"
Then click on volume received count
Then by default system should display "10" records as selected
Then system should display the record options as "10,25,50,100"
Then user selects "25" as option then system should display "25" records
Then user selects "50" as option then system should display "50" records
Then user selects "100" as option then system should display "100" records
Then user clicks on Next/Right arrow key then system should display next "100" records
Then click on download icon
Then Click on profile picture
And logout
@Yes
Scenario: To check whether user is able to see appropriate records when clicks on the total count on recon report
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Reconciliation Report"
Then click on total count
Then the count should match between total count and detailed report count
Then system should display the tabel headers as "BATCH CLASS, CLIENT CODE, COMMENT, DCN, DMR INGESTION TIME, DOC TYPE, FILE NAME, IMAGE COUNT, LOCATION/SITE, MAIL SORTER UID, PAGE COUNT, PROJECT CODE, RECEIVED DATE/TIME, SCAN DATE/TIME, SCANNING LOCATION, SORTER DATE/TIME, SOURCE, STATUS, TAT (HOURS), UNIQUE BARCODE"
Then Click on profile picture
And logout
@Yes
Scenario: To check that user should be able to go back only up to 6 months from current month to check and generate Recon Report 
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Reconciliation Report"
Then select from date as six months back from today
Then System should throw a toggle message as "You can only go back upto 6 months"
Then Click on profile picture
And logout
@Yes
Scenario: To check Download Recon Report Functionality when user clicks on Download button on Recon Report  and Recon Report Details Page.
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Reconciliation Report"
Then click on download icon
Then Click on profile picture
And logout

Scenario: To check whether user is able to cancel the request before PODtracked pull the data
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then select an email
Then select action as "Manage Physical delivery"
#----------------Need to work-------------------#

@yes
Scenario: To check whether when re-route action is performed mail move out from inbox.
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Batch_Name|Testing|12345|
|Batch_ID|Testing|12345|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then filter the DCN "autogeneratedDCN"
Then select an email
Then select action as "Re-Route"
Then enter receipient as "Chitra.test@yopmail.com" and select it
When click on send button
Then filter the DCN "autogeneratedDCN"
Then there should not be any record in the table
Then Click on profile picture
And logout
@Yes
Scenario: To check whether when completed action move to completed folder
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Batch_Name|Testing|12345|
|Batch_ID|Testing|12345|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter "autogeneratedDCN" and verify it is available
Then filter the DCN "autogeneratedDCN"
Then select an email
Then select action as "Completed"
Then click on Yes button
Then click on completed folder
Then filter the DCN "autogeneratedDCN"
Then "autogeneratedDCN" should be available in completed folder
Then Click on profile picture
And logout
@Yes
Scenario: To check whether when NMM action is performed mail moves to NMM folder and status changes accordingly 
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Batch_Name|Testing|12345|
|Batch_ID|Testing|12345|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter "autogeneratedDCN" and verify it is available
Then filter the DCN "autogeneratedDCN"
Then select an email
Then select action as "Not My Mail"
Then click on Yes button
Then click on NMM folder
Then filter the DCN "autogeneratedDCN"
Then "autogeneratedDCN" should be available in NMM folder
Then Click on profile picture
And logout
@Yes
Scenario: To check whether the Envelope view screen should have a button on the File Tab section named Open Full Mail
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then open full mail option should be avaliable in envelope mail
Then Click on profile picture
And logout
@Yes
Scenario: To check whether When I click on this button it should open the full mail like when I double click to open the mail
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then select an email
Then double click to open the email
Then Click on profile picture
And logout
@Yes
Scenario: To check whether user is able to see my entire mail with File, Annotation, Redaction and other tabs and options to scroll through the pages and meta data option, Action etc.
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then select an email
Then double click to open the email
Then system should display following mail header options
|HeaderOptions|
|Annotation|
|Redaction|
Then Click on profile picture
And logout

Scenario: To verify when a Mail is in the shared mailbox and is approaching the retention period the notification must be sent to the Shared mailbox email address
Then click on left pane menu "Project Setup"
Then filter the project name "Test123_project"
When click on edit.
Then click on doctype setup
Then click on adddoc type
#################------Need to work------##################
@pra
Scenario: To check mail user can add Canada Address in Manage Address
Then Click on profile picture
When   Click on Manage Address
Then filter the address "Home"
And delete it
When   Click on Add button
When click on drop down arrow "Address Type" 
Then system should display "Home,Office,Custom" address type options
Then click on below given dropdown arrow and select the below option and check the selected option
|dropdown|dropdownOption|
|Address Type|Custom|
|Address Type|Office|
|Address Type|Home|
Then enter address1 as "testing"
Then enter city as "Sudbury"
Then enter zipcode as "01776"
When   click on save button
Then User should successfully add Home address and get success msg as "Address saved successfully"
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then select an email
Then select action as "Manage Physical delivery"
Then select delivery preference as "Deliver To Address"
Then system should display the configured address "testing,Sudbury Ontario - 017726"
Then Click on profile picture
When   Click on Manage Address
Then filter the address "Home"
And delete it

Scenario: Check mail user able to add mobile number with a country code option in Manage Address
Then Click on profile picture
When   Click on Manage Address
When   Click on Add button
Then system should display "Home,Office,Custom" address type options
Then click on below given dropdown arrow and select the below option and check the selected option
|dropdown|dropdownOption|
|Address Type|Custom|
|Address Type|Office|
|Address Type|Home|
Then enter address1 as "testing"
Then enter city as "Sudbury"
Then enter zipcode as "01776"
Then enter phone number as "1234567890"
When   click on save button
Then User should successfully add Home address and get success msg as "Address saved successfully"
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then select an email
Then select action as "Manage Physical delivery"
Then select delivery preference as "Deliver To Address"
Then system should display the configured address "testing,Sudbury Ontario - 017726,+1-1234567890"
Then Click on profile picture
When   Click on Manage Address
Then filter the address "Home"
And delete it
@Yes
Scenario: To check whether user is able to click on nQube and see routing rule
Then click on toggle menu
Then click on left pane menu "nQube"
Then system should display sub menu option "Routing Rule"
Then Click on profile picture
And logout
@Yes
Scenario: To check whether user is able to click on routing rule and see the Invocation trigger, Rule condition and Rule execution
Then Click on profile picture
When click on Routing rule
When   click on add button
Then system should display routing rule options "Invocation Trigger,Rule Condition,Rule Execution"
Then Click on profile picture
And logout
@Yes
Scenario: To check whether user is able to add rule condition by selecting data for Field , Condition and  Value from dropdown
Then Click on profile picture
	When click on Routing rule
	When   click on add button
	When click on drop down arrow "project code" 
	When   select drop down option as "septClient_project"
	When   enter rule name as "TestRule17"
	When   click on trigger next button
	When   click on add button
	When click on drop down arrow "Field*" 
	When   select drop down option as "Batch Priority"
	When click on drop down arrow "Condition*" 
	When   select drop down option as "Equal"
	When    Enter value as "2"
	When   click on save button
	When   click on rule Next button
	When click on drop down arrow "Action*" 
	When   select drop down option as "Deliver Physically & Digitally"
	When select delivery prference as "Hold for Pick-up"
	When click on create button
	When click on rule save
	Then User should get success msg as "Auto routing details added successfully"
	Then filter the rule name "TestRule17"
	And delete it
@Yes
Scenario: To check whether field dropdown must comprise of additional dropdown items along with current dropdown items :Recipient City and Recipient state, Recipient Email.
Then Click on profile picture
	When click on Routing rule
	When   click on add button
	When click on drop down arrow "project code" 
	When   select drop down option as "septClient_project"
	When   enter rule name as "TestRule17"
	When   click on trigger next button
	When   click on add button
	When click on drop down arrow "Field*"
	Then system should display field options as "Document Type,Batch Class,Batch Priority,Sender Name,Recipient Name,Sender Email,Courier Name,Sender Company,Department,Keyword ,Location/Site,Scanning Location,Recipient City,Recipient State,Recipient Email"
@Yes
Scenario: To check whether user is able to see To dropdown on the screen in Action summary report
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Action Summary Report"
Then system should display from date and to date
Then Click on profile picture
And logout
@Yes
Scenario: To check whether when clicked on To, calendar should appear with current and past dates not with future dates in Action summary report
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Action Summary Report"
Then system should allow to select with current date
Then system should allow to select three days back from today
Then system should not allow to select ten days future from today
Then Click on profile picture
And logout
@Yes
Scenario: To check whether user see a new report in the Reports Menu named Audit Log Report
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Audit Log Report"
Then "Audit logs Report" should be displayed
Then Click on profile picture
And logout
@Yes
Scenario: To check whether user is able to see the dropdown option for client by default in Audit Log Report
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Audit Log Report"
When click on drop down arrow "Client" 
When   select drop down option as "septClient"
Then Click on profile picture
And logout
@Yes
Scenario: To check whether user is able to see the data when from and to date is selected in Audit Log Report
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Audit Log Report"
When select from date as "12/01/2020" and to date as "12/31/2020"
Then system should display "322" records
Then Click on profile picture
And logout
	
Scenario: To check whether user is able see Active user report in the dropdown
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Active User Report"
Then "Active User Report" should be displayed
Then Click on profile picture
And logout

Scenario: To check whether user is able to see  filter options for Client name, From and To Date , Project and Location/Site as filter options in Active User Report
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Active User Report"
Then system should display from date and to date
Then system should display client dropdown option
Then Click on profile picture
And logout

Scenario: To check whether user is able to see blank by default and When I select a From date the To date should be selected to current date by default in Active User Report
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Active User Report"
Then system should display blank data "No data available"
Then Click on profile picture
And logout

Scenario: To check whether user should be able to change the To date to any date till today's date in Active User Report
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Active User Report"
Then system should allow to select three days back from today
Then Click on profile picture
And logout

Scenario: To check whether fields should display Date,  no. of unique User's logged in to the DMR system, Project and Location/Site .
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Active User Report"
Then system should display the tabel headers as "DATE/TIME,No. of unique Users"
Then Click on profile picture
And logout

Scenario: To check whether all the fields are displayed under the report in Audit Log Report
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Audit Log Report"
Then system should display the tabel headers as "User Name,Module,Action,Date,Change,IP Address"
Then Click on profile picture
And logout

Scenario: To check whether user is able to download the report in Audit Log Report
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Audit Log Report"
Then click on download icon
Then Click on profile picture
And logout

Scenario: To check that popup is showing on page when user preferences selection is over using Customize drop down
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
When click on drop down arrow "Customize" 
When   select drop down option as "LABEL"
Then click on save preference
Then system should display the custom message "Do you want to save this preference for next login?"
Then Click on profile picture
And logout

Scenario: To check whether preferences are saved when 'Yes' button is clicked which is in popup which is showing on page when user preferences selection is over using Customize drop down
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
When click on drop down arrow "Customize" 
When   select drop down option as "LABEL"
Then click on save preference
Then system should display the custom message "Do you want to save this preference for next login?"
Then click on Yes button
Then system should display the tabel headers as "DCN,STATUS,TIME STAMP,SENDER,LABEL"
When click on drop down arrow "Customize" 
Then deselect the dropdown "LABEL"
Then click on save preference
Then click on Yes button
Then Click on profile picture
And logout

Scenario: To check preferences are saved when 'No' button is clicked which is in popup which is showing on page when user preferences selection is over using Customize drop down
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
When click on drop down arrow "Customize" 
When   select drop down option as "LABEL"
Then click on save preference
Then system should display the custom message "Do you want to save this preference for next login?"
Then click on NO button
Then system should display the tabel headers as "DCN,STATUS,TIME STAMP,SENDER"
Then Click on profile picture
And logout

Scenario: To check columns showing on page once browser refresh/ page refresh activity happened after saving the preferences for particular user
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
When click on drop down arrow "Customize" 
When   select drop down option as "LABEL"
Then click on save preference
Then system should display the custom message "Do you want to save this preference for next login?"
Then click on Yes button
Then system should display the tabel headers as "DCN,STATUS,TIME STAMP,SENDER,LABEL"
Then Switch to "CLIENTADMIN"
Then click OK button
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then system should display the tabel headers as "DCN,STATUS,TIME STAMP,SENDER,LABEL"
When click on drop down arrow "Customize" 
Then deselect the dropdown "LABEL"
Then click on save preference
Then click on Yes button
Then Click on profile picture
And logout

Scenario: To check whether user is able to see search option for quick search in Audit Log Report
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Audit Log Report"
Then search user "septClient sept2020"
And select the user "septClient sept2020"
Then verify system displays "septClient sept2020" records in the table
Then Click on profile picture
And logout

Scenario: To check whether user is able to see the client setup as a tab when logged in with Exelapp admin
Given navigate to given URL "https://exela-app-qa.exela.global/#/login" 
	Then enter username as "septclient"
	Then click on next button
	Then enter Password as "Pa$$w0rd"
	And click on signin button
	Then left pane menu "Client Setup" should be displayed
	Then Click on profile picture
    And logout
  
  Scenario: To check whether when user select a client to edit i should see the Menu setup as an option
Given navigate to given URL "https://exela-app-qa.exela.global/#/login" 
	Then enter username as "septclient"
	Then click on next button
	Then enter Password as "Pa$$w0rd"
	And click on signin button 
   Then click on left pane menu "Client Setup"
   Then filter client code "septclient"
   When   click on edit.
   Then edit client option "Menu Setup" should be displayed
   Then Click on profile picture
    And logout
    
    Scenario: To check whether user is able to see report as sub menu under menu setup
	Given navigate to given URL "https://exela-app-qa.exela.global/#/login" 
	Then enter username as "septclient"
	Then click on next button
	Then enter Password as "Pa$$w0rd"
	And click on signin button 
   Then click on left pane menu "Client Setup"
   Then click on edit client option "Menu Setup"
   When click on drop down arrow "Select Service Line*" 
	When   select drop down option as "DMR"
	Then system should display DMR options "Dashboard (dmr-dashboard),Client Setup (exela-client-setup),Role Setup (exela-client-role-setup),Project Setup (exela-project-setup),Site Design Setup (exela-storefront-setup),User Setup (exela-client-user-setup),User Permission (exela-user-permissions),nQube (no-link),ReachOut (no-link),Pulse Setup (pulse-setup),Reports (no-link),Inbox (mail-admin-inbox),Reconciliation Report (recon-report),Queue Management (dmr-queue-mgmt),user-dashboard (user-dashboard),Product Setup (exela-product-setup),Inbox (mail-user-inbox),Athena-Reports (no-link),Payments (payment-setup),Help Center (help-center)"
   Then Click on profile picture
    And logout
    
Scenario: To check whether user is  able to select DMR in the service line and should then show the list of all the DMR menus in the table below
Given navigate to given URL "https://exela-app-qa.exela.global/#/login" 
	Then enter username as "septclient"
	Then click on next button
	Then enter Password as "Pa$$w0rd"
	And click on signin button 
   Then click on left pane menu "Client Setup"
   Then click on edit client option "Menu Setup"
   When click on drop down arrow "Select Service Line*" 
	When   select drop down option as "DMR"
	Then click on DMR menu "Reports"
	Then system should display DMR Report sub menu options "Volume Report (reports/volume-report),Action Summary Report (reports/action-summary-report),Chain of Custody Report (reports/chain-of-custody-report),Reconciliation Report (reports/reconciliation-report),Reconciliation Report (reports/reconciliation-report),Blocked Senders Report (reports/blocked-senders-report),Inventory Report (reports/inventory-report),Volume By Source Report (reports/volume-by-source-report),Audit Report (reports/audit-report),Report Scheduler (reports/report-scheduler),Audit Log Report (reports/audit-logs-report),Active User Report (reports/active-user-report),Active User Report (reports/active-user-report),test (/test)"
	Then Click on profile picture
    And logout
    
 Scenario: To check whether user is able to select Reports as an option it should show the sub menus as Volume Report, Action Summary Report, Chain of Custody Report, Reconciliation Report, Inventory report, Retention Aging Report, Blocked Sender Report, Volume By Source Report and any new report that is added
Given navigate to given URL "https://exela-app-qa.exela.global/#/login" 
	Then enter username as "septclient"
	Then click on next button
	Then enter Password as "Pa$$w0rd"
	And click on signin button 
   Then click on left pane menu "Client Setup"
   Then click on edit client option "Menu Setup"
   When click on drop down arrow "Select Service Line*" 
	When   select drop down option as "DMR"
	Then click on DMR menu "Reports"
	Then system should all to select DMR Report sub menu options "Volume Report (reports/volume-report),Action Summary Report (reports/action-summary-report),Chain of Custody Report (reports/chain-of-custody-report),Reconciliation Report (reports/reconciliation-report),Reconciliation Report (reports/reconciliation-report),Blocked Senders Report (reports/blocked-senders-report),Inventory Report (reports/inventory-report),Volume By Source Report (reports/volume-by-source-report),Audit Report (reports/audit-report),Report Scheduler (reports/report-scheduler),Audit Log Report (reports/audit-logs-report),Active User Report (reports/active-user-report),Active User Report (reports/active-user-report),test (/test)"
	Then Click on profile picture
    And logout
    
    Scenario: To check whether user is able to select Reports as an option it should show the sub menus as Volume Report, Action Summary Report, Chain of Custody Report, Reconciliation Report, Inventory report, Retention Aging Report, Blocked Sender Report, Volume By Source Report and any new report that is added
Given navigate to given URL "https://exela-app-qa.exela.global/#/login" 
	Then enter username as "septclient"
	Then click on next button
	Then enter Password as "Pa$$w0rd"
	And click on signin button 
   Then click on left pane menu "Role Setup"
   Then click on Select client dropdown
   Then search the client "septclient" and select the client
   Then filter the role name "TestRole"
   When   click on edit.
	When click on edit role headers "Role-Menu Assignment"
	Then system should display DMR options "Dashboard (dmr-dashboard),Client Setup (exela-client-setup),Role Setup (exela-client-role-setup),Project Setup (exela-project-setup),Site Design Setup (exela-storefront-setup),User Setup (exela-client-user-setup),User Permission (exela-user-permissions),nQube (no-link),ReachOut (no-link),Pulse Setup (pulse-setup),Reports (no-link),Inbox (mail-admin-inbox),Reconciliation Report (recon-report),Queue Management (dmr-queue-mgmt),user-dashboard (user-dashboard),Product Setup (exela-product-setup),Inbox (mail-user-inbox),Athena-Reports (no-link),Payments (payment-setup),Help Center (help-center)"
	Then Click on profile picture
    And logout
    
Scenario: To check whether the selected menus are displayed under role setup menu for this client 
Given navigate to given URL "https://exela-app-qa.exela.global/#/login" 
	Then enter username as "septclient"
	Then click on next button
	Then enter Password as "Pa$$w0rd"
	And click on signin button 
   Then click on left pane menu "Role Setup"
   Then click on Select client dropdown
   Then search the client "septclient" and select the client
   Then filter the role name "TestRole"
   When   click on edit.
	When click on edit role headers "Role-Menu Assignment"   
	Then click on DMR menu "Reports" 
	Then system should all to select DMR Report sub menu options "Volume Report (reports/volume-report),Action Summary Report (reports/action-summary-report),Chain of Custody Report (reports/chain-of-custody-report),Reconciliation Report (reports/reconciliation-report),Reconciliation Report (reports/reconciliation-report),Blocked Senders Report (reports/blocked-senders-report),Inventory Report (reports/inventory-report),Volume By Source Report (reports/volume-by-source-report),Audit Report (reports/audit-report),Report Scheduler (reports/report-scheduler),Audit Log Report (reports/audit-logs-report),Active User Report (reports/active-user-report),Active User Report (reports/active-user-report),test (/test)"
	Then Click on profile picture
    And logout
    
 Scenario: To check if the Shared mailbox name is displayed in Chain of Custody report
 Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Sender Email|varshadighe3108@yopmail.com|varshadighe3108@yopmail.com|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Chain of Custody Report"
Then filter autogenerated DCN and verify it is available
Then system should display the user name as "SMB1"
Then Click on profile picture
And logout

Scenario: To check whether the created event have the user information captured as shared mailbox name as opposed to current System
 Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Sender Email|varshadighe3108@yopmail.com|varshadighe3108@yopmail.com|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Chain of Custody Report"
Then filter autogenerated DCN and verify it is available
Then system should display the user name as "SMB1"
Then system should display the event as "Action selected : Send To"
Then Click on profile picture
And logout

Scenario: Whenuser takes an action on it then the rest of the flow must follow as usual like the user's name must be then added in the User section and the action taken by him

 Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Batch_Name|Testing|12345|
|Batch_ID|Testing|12345|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Chain of Custody Report"
Then click on download icon
Then first record in excel against From column should be "" and TO column should be "varshadighe310891@yopmail.com"
Then Click on profile picture
And logout

Scenario: To check that From and To columns should show proper data in downloaded Chain of custody report when Re-route action is performed between one mail admin and another mail admin
 Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Batch_Name|Testing|12345|
|Batch_ID|Testing|12345|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter the DCN "autogeneratedDCN"
Then select an email
Then select action as "Re-Route"
Then enter receipient as "varshadighe31@yopmail.com" and select it
When click on send button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "CLIENTADMIN"
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Chain of Custody Report"
Then click on download icon
Then first record in excel against From column should be "" and TO column should be "varshadighe310891@yopmail.com"
Then Click on profile picture
And logout

Scenario: To check that From and To columns should show proper data in downloaded Chain of custody report when Re-route action is performed between one mail user and another mail user
 Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Batch_Name|Testing|12345|
|Batch_ID|Testing|12345|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter the DCN "autogeneratedDCN"
Then select an email
Then select action as "Re-Route"
Then enter receipient as "varshadighe31@yopmail.com" and select it
When click on send button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "CLIENTADMIN"
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Chain of Custody Report"
Then click on download icon
Then first record in excel against From column should be "" and TO column should be "varshadighe310891@yopmail.com"
Then Click on profile picture
And logout


Scenario: The Chain of custody report must show all the details which are visible on report page when I download the report

Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Chain of Custody Report"
Then click on download icon
Then report should display the coulmns "DCN	USER,DATE,EVENT,SOURCE,FROM,TO,FIELD,DELIVERY PRIORITY,DELIVERY INSTRUCTIONS,QUEUE,RECIPIENT,DOC TYPE"
Then Click on profile picture
And logout


Scenario: To check whether mail is received in Undeliverable mails folder and new mail on ingestion notification mail when file ingested contains Recipient name as blank and file ingested does not have matching criteria as mentioned in routing rule saved.
 Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Recipient Name|||
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then click on undelivered mail box
Then filter autogenerated DCN and verify it is available
Then Click on profile picture
And logout

Scenario: To check whether mail is received in Undeliverable mails folder of all mail admins when no routing rule is present and file is ingested for the  client
 Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Sender Email|varshadi@yopmail.com|varshadi@yopmail.com|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then click on undelivered mail box
Then filter autogenerated DCN and verify it is available
Then Click on profile picture
And logout

Scenario: To check the contents of mail received in Personal Inbox of user and new mail on ingestion notification when the file is successfully ingested for particular user and mail is received In personal folder in inbox with status as Unidentified recipient
 Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Recipient Name|||
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then click on undelivered mail box
Then filter autogenerated DCN and verify it is available
Then Click on profile picture
And logout

Scenario: To check the contents of mail received as new notification mail when users shared mailbox when new file is ingested for user  having access of shared mailbox folder
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Batch_Name|Testing|12345|
|Batch_ID|Testing|12345|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then status of the mail should be "New"
Then Click on profile picture
And logout

Scenario: To check whether user can see 7 days data by default when clicked on volume report
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Volume Report"
Then report should display "7" days data by default
Then Click on profile picture
And logout

Scenario: To check whether user can select data of only 1 month or 31 days period
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Volume Report"
Then select from date as today
Then report should display "31" days data
Then Click on profile picture
And logout

Scenario: To check whether To Date field is auto populated
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Volume Report"
Then select from date as today
Then report should display "31" days data
Then Click on profile picture
And logout

Scenario: To check whether user can see 7 days data by default when clicked on Recon report
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Reconciliation Report"
Then report should display "7" days data by default
Then Click on profile picture
And logout

Scenario: To check whether user is able to see from date and to date getting displayed for 7 days by default in Action summary report 
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Action Summary Report"
Then report should display "7" days data by default
Then Click on profile picture
And logout


