Feature: Test1
@Yes
Scenario: To check whether mail is received in Undeliverable mails folder and new mail on ingestion notification mail when file ingested contains Recipient name as blank and file ingested does not have matching criteria as mentioned in routing rule saved.
 Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Recipient Name|||
|Recipient Email|||
|Batch_Priority|aaa|aaa|
|Document_Type|test|test|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then click on undelivered mail box
Then filter autogenerated DCN and verify it is available
Then Click on profile picture
And logout
@Yes
Scenario: To check whether mail is received in Undeliverable mails folder of all mail admins when no routing rule is present and file is ingested for the  client
 Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Sender Email|varshadi@yopmail.com|varshadi@yopmail.com|
|Batch_Priority|aaa|aaa|
|Document_Type|test|test|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then click on undelivered mail box
Then filter autogenerated DCN and verify it is available
Then Click on profile picture
And logout
@Yes
Scenario: To check the contents of mail received in Personal Inbox of user and new mail on ingestion notification when the file is successfully ingested for particular user and mail is received In personal folder in inbox with status as Unidentified recipient
 Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Recipient Name|||
|Batch_Priority|2|2|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then status of the mail should be "Unidentified Recipient"
Then Click on profile picture
And logout
@Yes
Scenario: To check the contents of mail received as new notification mail when users shared mailbox when new file is ingested for user  having access of shared mailbox folder
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Batch_Priority|2|2|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then status of the mail should be "New"
Then Click on profile picture
And logout
@Yes
Scenario: To check whether user is able to see the client setup as a tab when logged in with Exelapp admin
Given navigate to given URL "https://exela-app-qa.exela.global/#/login" 
	Then enter username as "admin"
	Then click on next button
	Then enter Password as "Pa$$w0rd1"
	And click on signin button
	Then left pane menu "Client Setup" should be displayed
	Then Click on profile picture
    And logout
  @Yes
  Scenario: To check whether when user select a client to edit i should see the Menu setup as an option
Given navigate to given URL "https://exela-app-qa.exela.global/#/login" 
	Then enter username as "admin"
	Then click on next button
	Then enter Password as "Pa$$w0rd1"
	And click on signin button 
   Then click on Left pane menu "Client Setup"
   Then filter client code "septclient"
   When   click on edit.
   Then edit client option "Menu Setup" should be displayed
   Then Click on profile picture
    And logout
    @Yes
    Scenario: To check whether user is able to see report as sub menu under menu setup
	Given navigate to given URL "https://exela-app-qa.exela.global/#/login" 
	Then enter username as "admin"
	Then click on next button
	Then enter Password as "Pa$$w0rd1"
	And click on signin button 
   Then click on Left pane menu "Client Setup"
   Then filter client code "septclient"
   When   click on edit.
   Then click on edit client option "Menu Setup"
   When click on drop down Arrow "Select Service Line*" 
	When   select drop down Option as "DMR"
	Then system should display DMR options "Athena-Reports (no-link), Client Setup (exela-client-setup), Customers (no-link), Dashboard (dmr-dashboard), Help Center (help-center), Inbox (mail-admin-inbox), Inbox (mail-user-inbox), Payments (payment-setup), Product Setup (exela-product-setup), Project Setup (exela-project-setup), Pulse Setup (pulse-setup), Queue Management (dmr-queue-mgmt), ReachOut (no-link), Reconciliation Report (recon-report), Reports (no-link), Role Setup (exela-client-role-setup), Site Design Setup (exela-storefront-setup), User Permission (exela-user-permissions), User Setup (exela-client-user-setup), nQube (no-link), user-dashboard (user-dashboard)"
   Then Click on profile picture
    And logout
   @Yes
Scenario: To check whether user is  able to select DMR in the service line and should then show the list of all the DMR menus in the table below
Given navigate to given URL "https://exela-app-qa.exela.global/#/login" 
	Then enter username as "admin"
	Then click on next button
	Then enter Password as "Pa$$w0rd1"
	And click on signin button 
   Then click on Left pane menu "Client Setup"
   Then filter client code "septclient"
   When   click on edit.
   Then click on edit client option "Menu Setup"
   When click on drop down Arrow "Select Service Line*" 
	When   select drop down Option as "DMR"
	Then click on DMR menu "Reports"
	Then system should display DMR Report sub menu options "Action Summary Report (reports/action-summary-report), Active User Report (reports/active-user-report), Active User Report (reports/active-user-report), Audit Log Report (reports/audit-logs-report), Audit Report (reports/audit-report), Blocked Senders Report (reports/blocked-senders-report), Chain of Custody Report (reports/chain-of-custody-report), Inventory Report (reports/inventory-report), Reconciliation Report (reports/reconciliation-report), Report Scheduler (reports/report-scheduler), Retention Aging Report (reports/retention-aging-report), Volume By Source Report (reports/volume-by-source-report), Volume Report (reports/volume-report), test (/test)"
	Then Click on profile picture
    And logout
   @Yes
 Scenario: To check whether user is able to select Reports as an option it should show the sub menus as Volume Report, Action Summary Report, Chain of Custody Report, Reconciliation Report, Inventory report, Retention Aging Report, Blocked Sender Report, Volume By Source Report and any new report that is added
Given navigate to given URL "https://exela-app-qa.exela.global/#/login" 
	Then enter username as "admin"
	Then click on next button
	Then enter Password as "Pa$$w0rd1"
	And click on signin button 
   Then click on Left pane menu "Client Setup"
   Then filter client code "septclient"
   When   click on edit.
   Then click on edit client option "Menu Setup"
   When click on drop down Arrow "Select Service Line*" 
	When   select drop down Option as "DMR"
	Then click on DMR menu "Reports"
	Then system should all to select DMR Report sub menu options "Volume Report (reports/volume-report),Action Summary Report (reports/action-summary-report),Chain of Custody Report (reports/chain-of-custody-report),Reconciliation Report (reports/reconciliation-report),Reconciliation Report (reports/reconciliation-report),Blocked Senders Report (reports/blocked-senders-report),Inventory Report (reports/inventory-report),Volume By Source Report (reports/volume-by-source-report),Audit Report (reports/audit-report),Report Scheduler (reports/report-scheduler),Audit Log Report (reports/audit-logs-report),Active User Report (reports/active-user-report),Active User Report (reports/active-user-report),test (/test)"
	Then Click on profile picture
    And logout
    @Yes
    Scenario: To check whether user is able to select Reports as an option it should show the sub menus as Volume Report, Action Summary Report, Chain of Custody Report, Reconciliation Report, Inventory report, Retention Aging Report, Blocked Sender Report, Volume By Source Report and any new report that is added
Given navigate to given URL "https://exela-app-qa.exela.global/#/login" 
	Then enter username as "admin"
	Then click on next button
	Then enter Password as "Pa$$w0rd1"
	And click on signin button 
   Then click on Left pane menu "Role Setup"
   Then click on Select client dropdown
   Then search the client "septclient" and select the client
   Then filter the role name "TestRole"
   When   click on edit.
	When click on edit role headers "Role-Menu Assignment"
	Then system should display DMR options "Client Setup (exela-client-setup), Dashboard (dmr-dashboard), Inbox (mail-admin-inbox), Inbox (mail-user-inbox), Product Setup (exela-product-setup), Project Setup (exela-project-setup), Pulse Setup (pulse-setup), Queue Management (dmr-queue-mgmt), ReachOut (no-link), Reconciliation Report (recon-report), Reports (no-link), Role Setup (exela-client-role-setup), Site Design Setup (exela-storefront-setup), User Permission (exela-user-permissions), User Setup (exela-client-user-setup), nQube (no-link), user-dashboard (user-dashboard)"
	Then Click on profile picture
    And logout
   @Yes
Scenario: To check whether the selected menus are displayed under role setup menu for this client 
Given navigate to given URL "https://exela-app-qa.exela.global/#/login" 
	Then enter username as "admin"
	Then click on next button
	Then enter Password as "Pa$$w0rd1"
	And click on signin button 
   Then click on Left pane menu "Role Setup"
   Then click on Select client dropdown
   Then search the client "septclient" and select the client
   Then filter the role name "TestRole"
   When   click on edit.
	When click on edit role headers "Role-Menu Assignment"   
	Then click on DMR menu "Reports" 
	Then system should all to select DMR Report sub menu options "Volume Report (reports/volume-report),Action Summary Report (reports/action-summary-report),Chain of Custody Report (reports/chain-of-custody-report),Reconciliation Report (reports/reconciliation-report),Reconciliation Report (reports/reconciliation-report),Blocked Senders Report (reports/blocked-senders-report),Inventory Report (reports/inventory-report),Volume By Source Report (reports/volume-by-source-report),Audit Report (reports/audit-report),Report Scheduler (reports/report-scheduler),Audit Log Report (reports/audit-logs-report),Active User Report (reports/active-user-report),Active User Report (reports/active-user-report),test (/test)"
	Then Click on profile picture
    And logout
    @Yes
 Scenario: To check if the Shared mailbox name is displayed in Chain of Custody report
 Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Sender Email|varshadighe3108@yopmail.com|varshadighe3108@yopmail.com|
|Batch_Priority|2|2|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Chain of Custody Report"
Then filter autogenerated DCN and verify it is available
Then system should display the user name as "SMB1"
Then Click on profile picture
And logout
@Yes
Scenario: To check whether the created event have the user information captured as shared mailbox name as opposed to current System
 Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Recipient Name|test|test|
|Recipient Email|test@test.com|test@test.com|
|Sender Email|varshadighe3108@yopmail.com|varshadighe3108@yopmail.com|
|Document_Type|test|test|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Chain of Custody Report"
Then filter autogenerated DCN and verify it is available
Then system should display the user name as "SMB1"
Then system should display the event as "Action selected : Send To"
Then Click on profile picture
And logout
@Yes
Scenario: Whenuser takes an action on it then the rest of the flow must follow as usual like the user's name must be then added in the User section and the action taken by him

 Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Sender Email|varshadighe3108@yopmail.com|varshadighe3108@yopmail.com|
|Batch_Priority|2|2|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Chain of Custody Report"
Then click on download icon
Then first record in excel against From column should be "" and TO column should be "varshadighe310891@yopmail.com"
Then Click on profile picture
And logout
@Yes
Scenario: To check that From and To columns should show proper data in downloaded Chain of custody report when Re-route action is performed between one mail admin and another mail admin
 Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Sender Email|varshadighe3108@yopmail.com|varshadighe3108@yopmail.com|
|Batch_Priority|2|2|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter the DCN "autogeneratedDCN"
Then select an email
Then select action as "Re-Route"
Then enter receipient as "varshadighe31@yopmail.com" and select it
When click on send button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "CLIENTADMIN"
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Chain of Custody Report"
Then click on download icon
Then first record in excel against From column should be "" and TO column should be "varshadighe310891@yopmail.com"
Then Click on profile picture
And logout
@Yes
Scenario: To check that From and To columns should show proper data in downloaded Chain of custody report when Re-route action is performed between one mail user and another mail user
 Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Batch_Name|Testing|12345|
|Batch_ID|Testing|12345|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter the DCN "autogeneratedDCN"
Then select an email
Then select action as "Re-Route"
Then enter receipient as "varshadighe31@yopmail.com" and select it
When click on send button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "CLIENTADMIN"
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Chain of Custody Report"
Then click on download icon
Then first record in excel against From column should be "" and TO column should be "varshadighe310891@yopmail.com"
Then Click on profile picture
And logout