Feature: DMR Regression Suite Set2-2
@Yes
Scenario: To check changed current behaviour of loading entire PDF when opening mail with double click
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then double click to open the email
Then system should display nuber of pages count as "Total Pages: 775"
Then click on right arrow system should load next set of pages
Then click on left arrow system should load previous set of pages
Then for large files system should display the message "Annotation and Redaction restricted as this is a large file."
Then Click on profile picture
And logout
@Yes
Scenario: To check when user click on right arrow key in the pages loaded box it must load the next 100 pages

Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then double click to open the email
Then system should display nuber of pages count as "Total Pages: 775"
Then click on right arrow system should load next set of pages
Then click on left arrow system should load previous set of pages
Then for large files system should display the message "Annotation and Redaction restricted as this is a large file."
Then Click on profile picture
And logout
@Yes
Scenario: To check user can take all actions on the Large file
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then double click to open the email
Then system should display nuber of pages count as "Total Pages: 775"
Then click on right arrow system should load next set of pages
Then click on left arrow system should load previous set of pages
Then for large files system should display the message "Annotation and Redaction restricted as this is a large file."
Then Click on profile picture
And logout
@Yes
Scenario: To check user cant perform Send To actions on the Large file
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then select an email
Then select action as "Send To"
Then System should throw a toggle message as "Send To action restricted as this is a large file."
Then Click on profile picture
And logout
@Yes
Scenario: To check user can perform Send for Dry sign actions on the Large file
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then select an email
Then select action as "Send For DrySign"
Then System should throw a toggle message as "Send for drysign action restricted as this is a large file."
Then Click on profile picture
And logout

@Yes
Scenario: To check whether user is able to cancel the request before PODtracked pull the data  
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then select an email
Then select action as "Manage Physical delivery"
When select delivery prference as "Deliver To Locker"
When enter the delivery instruction as "testing"
When click on create button
Then filter autogenerated DCN and verify it is available
Then select an email
Then select action as "Manage Physical delivery"
Then click on yes button
When select delivery prference as "Deliver To Locker"
Then cancel the Physical delivery
Then Click on profile picture
And logout

@Yes
Scenario: To check whether user is able to take NMM action on cancel request mails  
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then select an email
Then select action as "Manage Physical delivery"
When select delivery prference as "Deliver To Locker"
When enter the delivery instruction as "testing"
When click on create button
Then filter autogenerated DCN
Then select an email
Then select action as "Manage Physical delivery"
Then click on yes button
When select delivery prference as "Deliver To Locker"
Then cancel the Physical delivery
Then filter autogenerated DCN
Then select an email
Then select action as "Not My Mail"
Then click on Yes button
Then System should throw a toggle message as "Digital mail rerouted successfully"
Then Click on profile picture
And logout
@Yes
Scenario: To check whether user is able to take Re-route action on cancel request mails  
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then select an email
Then select action as "Manage Physical delivery"
When select delivery prference as "Deliver To Locker"
When enter the delivery instruction as "testing"
When click on create button
Then filter autogenerated DCN
Then select an email
Then select action as "Manage Physical delivery"
Then click on yes button
When select delivery prference as "Deliver To Locker"
Then cancel the Physical delivery
Then filter autogenerated DCN
Then select an email
Then select action as "Re-Route"
Then enter receipient as "mailuserauto@yopmail.com" and select it
When click on send button
Then System should throw a toggle message as "Digital mail rerouted successfully"
Then Click on profile picture
And logout
@Yes
Scenario: To check whether user is able to take completed action on cancel request mails  
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then select an email
Then select action as "Manage Physical delivery"
When select delivery prference as "Deliver To Locker"
When enter the delivery instruction as "testing"
When click on create button
Then filter autogenerated DCN
Then select an email
Then select action as "Manage Physical delivery"
Then click on yes button
When select delivery prference as "Deliver To Locker"
Then cancel the Physical delivery
Then filter autogenerated DCN
Then select an email
Then select action as "Completed"
Then click on Yes Button
Then System should throw a toggle message as "Action applied to selected mail items"
Then Click on profile picture
And logout

@Yes
Scenario: To check whether user is able to take NMM action on cancel request mails  
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then select an email
Then select action as "Manage Physical delivery"
When select delivery prference as "Deliver To Locker"
When enter the delivery instruction as "testing"
When click on create button
Then filter autogenerated DCN
Then select an email
Then select action as "Manage Physical delivery"
Then click on yes button
When select delivery prference as "Deliver To Locker"
Then cancel the Physical delivery
Then filter autogenerated DCN
Then select an email
Then select action as "Not My Mail"
Then click on Yes button
Then click on NMM folder
Then filter autogenerated DCN and verify it is available
Then Click on profile picture
And logout

@Yes
Scenario: To check whether user is able to change status from 'physical Handling Requested' to 'Delivery In progress' on any small size file/mail when  action 'Manage Physical Delivery' is performed on it 
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then select an email
Then select action as "Manage Physical delivery"
When select delivery prference as "Deliver To Locker"
When enter the delivery instruction as "testing"
When click on create button
Then Hit the pod tracker API for user "sepclient"
Then the responce code should be "200"
Then refresh the page
Then filter autogenerated DCN
Then status of the email should be "Delivery In Progress"
Then Click on profile picture
And logout
@Yes
Scenario: To check whether user is able to change status from 'physical Handling Requested' to 'Delivery In progress' on any large size file/mail when  action 'Manage Physical Delivery' is performed on it  
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then select an email
Then select action as "Manage Physical delivery"
When select delivery prference as "Deliver To Locker"
When enter the delivery instruction as "testing"
When click on create button
Then Hit the pod tracker API for user "sepclient"
Then the responce code should be "200"
Then refresh the page
Then filter autogenerated DCN
Then status of the email should be "Delivery In Progress"
Then Click on profile picture
And logout

@Yes
Scenario: To check that whether user should not be able to cancel physical delivery request when status is delivery in progress   
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then select an email
Then select action as "Manage Physical delivery"
When select delivery prference as "Deliver To Locker"
When enter the delivery instruction as "testing"
When click on create button
Then Hit the pod tracker API for user "sepclient"
Then the responce code should be "200"
Then refresh the page
Then filter autogenerated DCN
Then status of the email should be "Delivery In Progress"
Then select an email
Then select action as "Manage Physical delivery"
Then System should throw a toggle message as "You cannot perform manage physical delivery action on mail with Delivery In Progress status"
Then Click on profile picture
And logout
@Yes
Scenario: User should not be able to perform any of the actions like Re-route, Not My Mail, Delete, Junk Mail, Manage Physical Delivery, Send For Drysign and Completed from Inbox page on mails having status  'Delivery in Progress'
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then select an email
Then select action as "Manage Physical delivery"
When select delivery prference as "Deliver To Locker"
When enter the delivery instruction as "testing"
When click on create button
Then Hit the pod tracker API for user "sepclient"
Then the responce code should be "200"
Then refresh the page
Then filter autogenerated DCN
Then status of the email should be "Delivery In Progress"
Then select an email
Then select action as "Re-Route"
Then System should throw a toggle message as "You cannot perform re-route action on mail with Delivery In Progress status."
Then Click on profile picture
And logout

@Yes
Scenario: User should  be able to perform any of the actions like Send To, Move To Folder, Manage Label from Inbox page or from Mail Viewer page on mails having status 'Delivery in Progress'
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged-1-25-Pages.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then select an email
Then select action as "Manage Physical delivery"
When select delivery prference as "Deliver To Locker"
When enter the delivery instruction as "testing"
When click on create button
Then Hit the pod tracker API for user "sepclient"
Then the responce code should be "200"
Then refresh the page
Then filter autogenerated DCN
Then status of the email should be "Delivery In Progress"
Then select an email
Then select action as "Send To"
Then enter recepient as "testclient20@yopmail.com" and select it
When click on send butn
Then click on send mail button
Then System should throw a toggle message as "Digital Mail Sent successfully"
Then Click on profile picture
And logout
@Yes
Scenario: User should  be able to perform any of the actions like Send To, Move To Folder, Manage Label from Inbox page or from Mail Viewer page on mails having status 'Delivery in Progress'
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then select an email
Then select action as "Manage Physical delivery"
When select delivery prference as "Deliver To Locker"
When enter the delivery instruction as "testing"
When click on create button
Then Hit the pod tracker API for user "sepclient"
Then the responce code should be "200"
Then refresh the page
Then filter autogenerated DCN
Then status of the email should be "Delivery In Progress"
Then select an email
Then double click to open the email
When click on drop down arrow "Status"
Then "Delivery In Progress" should be available in the dropdown
When   select drop down option as "Delivery In Progress"
Then Click on profile picture
And logout
@Yes
Scenario: To check that whether file/count is showing in Processed column in Recon report when user tried to ingest file which now not having duplicate DCN
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
|Received_Date|20210128|20210128|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Reconciliation Report"
Then filter the received date "01/28/2021"
Then click on processed count
Then filter autogenerated DCN and verify it is available
Then Click on profile picture
And logout
@Yes
Scenario: To check that whether correct received date is showing for file in Recon Report when file is ingested through Open box API in DMR application for particular client 
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
|Received_Date|20210128|20210128|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Reconciliation Report"
Then filter the received date "01/28/2021"
Then click on processed count
Then filter autogenerated DCN and verify it is available
Then recived date should be "01-28-2021 12:00:00" for the email
Then Click on profile picture
And logout
@Yes
Scenario: To check that whether correct received time [received time in xml - (time zone in xml in hrs) and then subtract 5 hr from that value] is showing for file in Recon Report when file is ingested through Open box API in DMR application for particular client  
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
|Received_Date|20210128|20210128|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Reconciliation Report"
Then filter the received date "01/28/2021"
Then click on processed count
Then filter autogenerated DCN and verify it is available
Then recived date should be "01-28-2021 12:00:00" for the email
Then Click on profile picture
And logout
@Yes
Scenario: To check that functionality of link Total Volume link on Recon report summary/details report   
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
|Received_Date|20210128|20210128|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Reconciliation Report"
Then click on total count
Then the count should match between total count and detailed report count
Then Click on profile picture
And logout
@Yes
Scenario: To Verify User should get only one email  after ingestion of files. 
Then navigate to given URL "http://www.yopmail.com/en/"
Then enter yopmail id as "varshadighe3108@yopmail.com"
When click on check inbox
Then click on delete dropdown
Then click on empty inbox
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then refresh the page
Then system should display "You Got Mail" email
@praveentes
Scenario: To check whether the same behaviour is also applied for user routing rule 
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
	When click on Routing rule
	When   click on add button
	When click on drop down arrow "project code" 
	When   select drop down option as "septClient_project"
	When   enter rule name as "TestRule17"
	When   click on trigger next button
	When   click on add button
	When click on drop down arrow "Field*"
	Then system should display field options as "Document Type,Batch Class,Batch Priority,Sender Name,Recipient Name,Sender Email,Courier Name,Sender Company,Department,Keyword ,Location/Site,Scanning Location,Recipient City,Recipient State,Recipient Email"
@Yes
Scenario: Verify client admin is able to add roles and newly created roles should see assinged menus after login.
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
	Then click on toggle menu
	Then click on left pane menu "Role Setup"
	Then filter the role name "Test Role Testing"
	And delete it
	When   click on add role button
	When   Enter Rolename as "Test Role Testing" 
	When click on drop down arrow "Role Type*" 
	When   select drop down option as "Mail User"
	When click on drop down arrow "Product*" 
	When   select drop down option as "DMR"
	When   click on save button 
	Then User should get success msg as "Role has been added successfully"
	Then filter the role name "Test Role Testing"
	When   click on edit.
	When click on edit role headers "Role-Menu Assignment"
	When    check the checkbox of menus from  Role menu assignment tab as "Dashboard (dmr-dashboard)", "Inbox (mail-user-inbox)" and "Reports (no-link)"
	When   Click on assign button
    Then User should get Success msg as "Menus has been added Successfully"
    When click on edit role headers "Role-Project Assignment"
    #When click on "Role-Project Assignment" role option
    When click on drop down arrow "Select Project*" 
	When   select drop down option as "septClient_project"
	When    check the project queue as "Default"
	When   click on assign
    Then User should get success msg as "Project queue access updated Successfully"
    When click on edit role headers "Role-Shared-Mailbox Assignment"
	When   Check the shared mail box as "Testing shared mailbox" from role shared mailbox assignment tab.
	Then click on left pane menu "User Setup"
	Then filter login name "varsha001"
	When   click on edit.
	When click on drop down arrow "Assign Roles*" 
	When   select drop down option as "Test Role Testing"
	When   click on SAVE button
	Then Click on profile picture
	And logout
	Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
	Then enter username as "varsha001"
	Then click on next button
	Then enter Password as "Pa$$w0rd"
	And click on signin button
	Then click on toggle menu
	Then left pane should consists of "Dashboard,Inbox,Reports"
	Then Click on profile picture
	And logout
	Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
	Then enter username as "septclient"
	Then click on next button
	Then enter Password as "Pa$$w0rd"
	And click on signin button
	Then click on toggle menu
	Then click on left pane menu "Role Setup"
	Then filter the role name "Test Role Testing"
	And delete it
	
	@Yes
Scenario: Validate Junk mail action is working
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged-1-25-Pages.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then select an email
Then select action as "Junk Mail"
Then click on Yes button
Then User should get success msg as "Action applied to selected mail items"
Then click on Deleted Items folder
Then filter autogenerated DCN and verify it is available
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "CLIENTADMIN"
Then click OK button
Then click on toggle menu
Then click on left pane menu "Reports"
Then click on the report "Action Summary Report"
Then filter the action "Junk Mail"
Then click on count that is showing
Then the junk mail count and total detailed count should be equal

@Yes
Scenario: Validate Not my mail Action is working
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged-1-25-Pages.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then select an email
Then select action as "Not My Mail"
Then Enter Email id as  "mailuserauto@yopmail.com" in Do_you_want_to_suggest_any_other_user_name?
Then click on Yes button
Then User should get success msg as "Digital mail rerouted successfully"
Then Click on profile picture
And logout
Then navigate to given URL "http://www.yopmail.com/en/"
Then enter yopmail id as "mailuserauto@yopmail.com"
When click on check inbox
Then system should display "Digital Mail - Re-Route Notification" email

@Yes
Scenario: Validate Delete mail Action is working
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged-1-25-Pages.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then select an email
Then select action as "Delete"
Then User should get success msg as "Action applied to selected mail items" 
Then click on Deleted Items folder
Then filter autogenerated DCN and verify it is available

@Yes
Scenario: Validate Physical delivery Action is working
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged-1-25-Pages.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
When Click on Manage Address
Then filter the address "Office"
And delete it
When   Click on Add button
When click on drop down arrow "Address Type" 
When select drop down option as "Office" 
When Add Address Name as "S B ROAD Pune", Desk Number as "209" , Floor number as "9" ,mobileno. as "8099685985" ,city as "Pune" ,state as "Maharastra" ,country as "India" ,zip code as "411057"
When click on save button
Then User should successfully add Office address and get success msg as "Address saved successfully"
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then select an email
Then select action as "Manage Physical delivery"
Then click on Create button
Then User should get success msg as "Action applied to selected mail items"
Then Click on profile picture
When Click on Manage Address
Then filter the address "Office"
And delete it

@Yes
Scenario: Validate Completed Action is working
Then update the "Base.xml" with below values and zip it with "document_2_envelope_page_1.pdf" and "merged-1-25-Pages.pdf"
|FieldName|CapturedValue|Value|
|Document_Type|Human Resource|Human Resource|
Then ingest the above zipped file to Azure Blob Storage
Then navigate to given URL "https://dmr-qa.exela.global/#/login" 
Then enter username as "septclient"
Then click on next button
Then enter Password as "Pa$$w0rd"
And click on signin button
Then Click on profile picture
Then Click on SwitchTo option
Then Switch to "Mail Admin(Mail User)"
Then click OK button
Then filter autogenerated DCN and verify it is available
Then select an email
Then select action as "Completed"
Then click on Yes Button
Then User should get success msg as "Action applied to selected mail items"
Then click on Completed folder
Then filter autogenerated DCN and verify it is available
	